### ISSUE TITLE
`caprover deploy --default` hangs at the: `Ensuring authentication...` step

### ISSUE THREAD

**Issue by neil-rubens** [caprover/caprover-cli#94] opened 2021-05-08 03:30 UTC
`caprover deploy`  works fine; 

but when I try to use :
`caprover deploy --default` 

it hangs at the: 
`Ensuring authentication...`

p.s. ❤️ using caprover

**Comment by githubsaturn** [comment] 2021-05-08 14:38
Duplicate of https://github.com/caprover/caprover-cli/issues/36

Looks like it's only a windows problem.

**Closed by githubsaturn** 2021-05-08 14:38 UTC

**Comment by neil-rubens** [comment] 2021-05-08 22:14
> Looks like it's only a windows problem.

Indeed, am on Windows 10.
