### ISSUE TITLE
stuck/hangs when deploying

### ISSUE THREAD

**Issue by eikaramba** [caprover/caprover-cli#125] opened 2022-07-12 13:39 UTC
I have the very strange issue that the deployment is stuck/hangs at the very last confirmation step. no matter whether interactive or not.
But if i hint ENTER again i get the confirmation message again and it continues
![grafik](https://user-images.githubusercontent.com/1320525/178502876-6fa23576-1c00-41f8-85cc-8f8ebee7142f.png)

You can see there that i first enter "Y" and hit enter. then i see nothing and can wait forever. but as soon as i hit ENTER again it continues.

I don't recollect that this was the case in the past. but it is happening now and reinstalling everything did not help. it is NOT a criticial issue, the only downside is that in the non-interactive mode i still need to do it. but on windows i am not using this mode.

Windows 10
node 16.160
latest caprover

I am basically posting it here because i spent way too long trying to fix the error until i discovered i can just hit enter again 🤣

**Comment by githubsaturn** [comment] 2022-07-31 15:36
Dupe of https://github.com/caprover/caprover-cli/issues/88

**Closed by githubsaturn** 2022-07-31 15:36 UTC
