### ISSUE TITLE
No longer see build progress in CLI

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover-cli#28] opened 2019-08-22 15:44 UTC
Not sure yet what the pattern is, but sometimes now when I deploy my app via the CLI there are no progress reports like there used to be... I just get:

    This might take several minutes. PLEASE BE PATIENT...

and then *immediately* it returns to the command prompt (no need to be patient!).

But in the build logs of the console the build process is shown (like it used to be in the CLI), so the build is progressing after all.

If this is deliberate, I think I prefer it how it used to be, where you can see what is going on in the place where you actually set the build going.

**Comment by githubsaturn** [comment] 2019-08-22 15:50
This could be a CLI or the server bug. The build pipeline has recently been refactored.

1) Can you please downgrade your CLI via `npm install -g caprover@1.2.0` and see whether you're still experiencing the issue?
2) What version of CapRover are you running on your server?

**Comment by drmrbrewer** [comment] 2019-08-22 16:06
> 1. Can you please downgrade your CLI via `npm install -g caprover@1.2.0` and see whether you're still experiencing the issue?

Downgraded, and so far I haven't seen this issue.

> 2. What version of CapRover are you running on your server?

The very latest... as always... `1.5.2`.

I should add that I happened to notice that a newly-added docker swarm node had no load, despite re-scaling several of my apps, whereas other nodes had high load.  I did a `docker node ps rxlzfd3eiywjt8zsmyv7i1bdd` on that node, and there were lots of `Rejected 2 minutes ago   "No such image: registry.myserv…" (truncated message).  Not sure whether this is related or not to the new CLI.

**Comment by githubsaturn** [comment] 2019-08-22 16:10
`No such image: registry.myserv...` has nothing to do with CLI. Most probably, it's even not related to CapRover per se... It's either:
- Firewall issue: make sure necessary ports are open: https://caprover.com/docs/firewall.html
- registry issue: if you're using a 3rd party registry, make sure your password and etc is correct.
- Docker issue: just a bug in Docker swarm?

**Comment by drmrbrewer** [comment] 2019-08-22 16:16
> nothing to do with CLI

You said above that "This could be a CLI or the server bug. The build pipeline has recently been refactored." 

So it could be a CapRover server bug not a CLI bug then?

firewall: possibly but I use a server image that has firewall disabled by default (and I've never had a problem before) so I doubt it.

registry: I don't use a 3rd party registry.

docker issue: possible I guess.

**Comment by githubsaturn** [comment] 2019-08-22 16:19
> So it could be a CapRover server bug not a CLI bug then?

Correct. There's a small chance that it's a CapRover server bug. Is it easy to reproduce with any newly added node?

**Comment by drmrbrewer** [comment] 2019-08-22 16:23
I'll keep an eye on it.  The context here is that I have an automated process which scales up when high server (swarm) load is detected.  Once the new server has been spun up and has been added to the swarm, I wait a short time and then re-scale app instances (to ensure that the new server is actually used, i.e. so that existing services are spread across all available nodes including the new one).  I'll check that there isn't a timing issue relating to that, but it's worked flawlessly for a long time now and I've not noticed a problem before now where a new node was not utilised.

**Comment by drmrbrewer** [comment] 2019-08-22 19:25
@githubsaturn though to be clear, the issue reported in the original post definitely seems to be a bug that needs addressing?  That is in response to a manual deploy, nothing to do with auto scaling.  Not showing build progress in the CLI (only in the build logs panel of the caprover server) doesn't seem correct.

**Comment by githubsaturn** [comment] 2019-08-23 13:48
I was hoping this was a server issue, but since you downgraded to the previous version of CLI, you're not seeing this issue. So it tells me this is a CLI issue. I'll look into this asap.

**Comment by githubsaturn** [comment] 2019-08-23 15:19
Fixed in https://github.com/caprover/caprover-cli/commit/94adca0a4b087c2bc36faf15e972b61ed6cff336

v2.0.2

**Closed by githubsaturn** 2019-08-23 15:19 UTC

**Comment by drmrbrewer** [comment] 2019-08-23 15:22
When will this be available to try?

**Comment by githubsaturn** [comment] 2019-08-23 15:23
Now

**Comment by drmrbrewer** [comment] 2019-08-23 16:50
OK I've upgraded to v2.0.2 and will see how it goes.  So far, so good.
