### ISSUE TITLE
Default Deployment get's stuck

### ISSUE THREAD

**Issue by Tam2** [caprover/caprover-cli#75] opened 2021-01-15 12:08 UTC
When using `caprover deploy` and walking through the steps the deployment works correctly.

Then on the same project running `caprover deploy -d` the process hangs at `Ensuring authentication`

```
PS C:\project> caprover deploy -d


------------
CapRover CLI has recently been refactored. Please report potential bugs here: https://github.com/caprover/caprover-cli/issues
------------


Preparing deployment to CapRover...

Ensuring authentication...
```

**Comment by githubsaturn** [comment] 2021-01-15 13:05
Duplicate of this: https://github.com/caprover/caprover-cli/issues/36

**Closed by githubsaturn** 2021-01-15 13:05 UTC
