### ISSUE TITLE
Title: Issue with Constant.ts file not reflecting environment variable override in built Constants.js

### ISSUE THREAD

**Issue by kmikodev** [caprover/caprover-cli#142] opened 2024-03-12 22:43 UTC
I've encountered an inconsistency when using the latest version of the CapRover library. Upon installation, the Constant.ts file within the utils directory contains the following line:

```
const ADMIN_DOMAIN = process.env.CAPROVER_ADMIN_DOMAIN_OVERRIDE || 'captain';
```

However, after installation, when inspecting the Constants.js file in the built/utils directory, the line appears as:

```
const ADMIN_DOMAIN = 'captain';
```

I've cloned the master branch and executed the compilation command, which seems to produce the correct output. Additionally, I've published a new version ([caprover-fix](https://www.npmjs.com/package/caprover-fix)) on npm for further testing.

This inconsistency appears to result in the environment variable override not being reflected in the built Constants.js file. Could you please investigate this issue? Let me know if you need any further information or assistance in resolving this matter. Thank you!

**Comment by githubsaturn** [comment] 2024-03-14 04:19
Feel free to open the pull request to fix if you have the fix for this.

**Comment by kmikodev** [comment] 2024-04-23 08:07
OK, I will check this in the future, actually I'm using 
![image](https://github.com/caprover/caprover-cli/assets/5812384/211dc524-22ca-41c7-807f-dc26c1f4dc5c)

**Comment by wildyaboku** [comment] 2024-07-03 00:46
@githubsaturn FYI there doesn't seem to be a PR-able "fix" for this. It looks more like an issue with your GitHub Action workflows or something. The built files don't match the source files in 2.3.0.

**Comment by githubsaturn** [comment] 2024-07-03 01:15
> there doesn't seem to be a PR-able "fix" for this

I'm not sure what this means. If it's not PR-able fix, then what fix should be implemented. Even Github Action workflows are part of the source code here:
https://github.com/caprover/caprover-cli/blob/master/.github/workflows/build_push_docker_release.yml

So anything should be possible.

**Comment by wildyaboku** [comment] 2024-07-03 01:23
Hi @githubsaturn, I looked more into the workflows. I don't see where the `npm publish` command is in this repo.

In short:

- The dockerfile in the repository builds the code correctly
- The `build` script in the package.json builds the code correctly

And yet, the source code published to NPM does not match what is built in either case.

Did you run `npm publish` manually on your end? Are you certain that it was using freshly built files? Because it really doesn't look that way.

Apologies for my former brevity.

**Comment by githubsaturn** [comment] 2024-07-03 01:32
Ah that makes sense!

**Comment by githubsaturn** [comment] 2024-07-03 01:34
I completely missed that the actions on github are for the Docker images. https://hub.docker.com/r/caprover/cli-caprover

**Comment by githubsaturn** [comment] 2024-07-03 01:38
Just published 2.3.1 - can you please confirm if it's fixed?

**Comment by wildyaboku** [comment] 2024-07-03 01:43
Yes, I can confirm it is working now, and the source code of the built file matches what is expected.

Thank you @githubsaturn!

**Comment by githubsaturn** [comment] 2024-07-03 01:47
Thanks! I should definitely add npm publish to GitHub action!

**Closed by githubsaturn** 2024-07-03 01:47 UTC
