### ISSUE TITLE
Freezes on ensuring authentication when machine name provided from command line

### ISSUE THREAD

**Issue by dmwyatt** [caprover/caprover-cli#61] opened 2020-08-19 18:00 UTC
If I just run `caprover deploy`, `caprover deploy -a THE_APP`, or `caprover deploy -a THE_APP -p THE_PASSWORD` I can step through the interactive prompts just fine<sup>*</sup>.

If I include the machine name it just does the following.  I've let it set for 20+ minutes.  It usually takes less than 5 for a deploy.

This is on Windows 10 with Powershell or cmd.

```
⪫ caprover deploy -a THE_APP -n THE_MACHINE -p THE_PASSWORD

------------
CapRover CLI has recently been refactored. Please report potential bugs here: https://github.com/caprover/caprover-cli/issues
------------


Preparing deployment to CapRover...

**** Protip ****
You seem to have deployed THE_APP from this directory in the past, use --default flag to avoid having to re-enter the information.

**** Warning ****
No captain-definition was found in main directory: unless you have specified a special path for your captain-definition, this build will fail!

Ensuring authentication...
```
<hr/>
<sup>*</sup> Except for the fact that I always have to press enter twice after accepting the warning that uncommited and gitignored files will not be pushed.  If I only press it once, it looks like the script has frozen.

**Comment by githubsaturn** [comment] 2020-08-20 01:55
Duplicate of https://github.com/caprover/caprover-cli/issues/36

Unfortunately I don't have a windows box, so we'll have to wait for a contributor to fix this.

**Closed by githubsaturn** 2020-08-20 01:55 UTC
